database:
  dialect: mysql
  user:
  password:
  host:
  port:
  dbname:
  max_idle_conns:
  max_open_conns:


gin:
  mode: debug

session:
  size: 10
  network: tcp
  address:
  password:
  keyPairs:
