database:
  dialect: mysql
  user:
  password:
  host:
  port: 3306
  dbname: easy-upgrade
  max_idle_conns: 10
  max_open_conns: 100
  auto_migrate: false

gin:
  mode: debug

session:
  size: 10
  network: tcp
  address:
  password:
  db: 10
  keyPairs:
  expires-time: 604800

rpc:
  eth-mainnet:
  polygo_mainnet:
  goerli_testnet:
  wallaby_testnet: wss://wallaby.node.glif.io/rpc/v0

email:
  authCode:
  email:
  username:
