basePath: /api
definitions:
  models.Contract:
    properties:
      contractHistoryArr:
        items:
          $ref: '#/definitions/models.ContractHistory'
        type: array
      createdAt:
        type: integer
      email:
        type: string
      id:
        type: integer
      lastUpdate:
        type: integer
      name:
        type: string
      network:
        description: chain id
        type: integer
      proxyAddress:
        type: string
      proxyOwner:
        type: string
      updatedAt:
        type: integer
      userID:
        type: integer
    type: object
  models.ContractHistory:
    properties:
      contractId:
        type: integer
      createdAt:
        type: integer
      id:
        type: integer
      network:
        description: chain id
        type: integer
      newOwner:
        type: string
      previousOwner:
        type: string
      updateBlock:
        type: integer
      updateTX:
        type: string
      updateTime:
        type: integer
      updatedAt:
        type: integer
    type: object
  request.Contract:
    properties:
      contractName:
        type: string
      email:
        type: string
      network:
        description: chain id
        type: integer
      proxyAddress:
        type: string
    type: object
  request.Login:
    properties:
      address:
        type: string
      signData:
        type: string
      signature:
        type: string
    type: object
  request.UpdateEmail:
    properties:
      email:
        type: string
    type: object
  response.PageResult:
    properties:
      list: {}
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  response.RespResult:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.UserInfo:
    properties:
      address:
        type: string
      email:
        type: string
      expiresAt:
        type: integer
      id:
        type: integer
      name:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
  title: easy-upgrade-backend
  version: 1.0.0
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login param
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.RespResult'
            - properties:
                data:
                  $ref: '#/definitions/response.UserInfo'
              type: object
      summary: User login
      tags:
      - auth
  /notifier:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        type: string
      - description: page number
        in: query
        name: pageNum
        type: integer
      - description: page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.RespResult'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/response.PageResult'
                  - properties:
                      list:
                        items:
                          $ref: '#/definitions/models.Contract'
                        type: array
                    type: object
              type: object
      security:
      - ApiKeyAuth: []
      summary: page query notify event
      tags:
      - notify
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        type: string
      - description: add notifier param
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Contract'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.RespResult'
            - properties:
                data:
                  $ref: '#/definitions/models.Contract'
              type: object
      security:
      - ApiKeyAuth: []
      summary: create notify event
      tags:
      - notify
  /notifier/history:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        type: string
      - description: contract id
        in: query
        name: contractID
        required: true
        type: integer
      - description: page number
        in: query
        name: pageNum
        type: integer
      - description: page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.RespResult'
            - properties:
                data:
                  $ref: '#/definitions/models.Contract'
              type: object
      security:
      - ApiKeyAuth: []
      summary: page query update history
      tags:
      - notify
  /user/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        type: string
      - description: update user email
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RespResult'
      security:
      - ApiKeyAuth: []
      summary: update user email
      tags:
      - auth
schemes:
- http
- https
swagger: "2.0"
